"""priorauth foundation

Revision ID: 48f4144d5f9c
Revises: 
Create Date: 2026-06-17 17:18:04.018896
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '48f4144d5f9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_membership_user_org', 'organization_memberships', ['user_id', 'organization_id'], unique=True)
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('prior_auth_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=64), nullable=True),
    sa.Column('patient_label', sa.String(length=255), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('requested_service', sa.String(length=255), nullable=False),
    sa.Column('service_code', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('case_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_org_status', 'prior_auth_cases', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_prior_auth_cases_organization_id'), 'prior_auth_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prior_auth_cases_status'), 'prior_auth_cases', ['status'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('run_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_case_id'), 'analysis_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_organization_id'), 'analysis_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_run_type'), 'analysis_runs', ['run_type'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=64), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index('ix_documents_case_type', 'documents', ['case_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_heading', sa.String(length=255), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_case_type', 'document_chunks', ['case_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_case_id'), 'document_chunks', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_type'), 'document_chunks', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_vector_id'), 'document_chunks', ['vector_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_case_id'), 'document_pages', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_organization_id'), 'document_pages', ['organization_id'], unique=False)
    op.create_table('policy_criteria',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=True),
    sa.Column('criterion_code', sa.String(length=32), nullable=False),
    sa.Column('criterion_type', sa.String(length=64), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('required_evidence', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_page', sa.String(length=64), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ambiguity_notes', sa.JSON(), nullable=False),
    sa.Column('extraction_version', sa.Integer(), nullable=False),
    sa.Column('reviewer_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_criteria_case_code', 'policy_criteria', ['case_id', 'criterion_code'], unique=False)
    op.create_index(op.f('ix_policy_criteria_case_id'), 'policy_criteria', ['case_id'], unique=False)
    op.create_index(op.f('ix_policy_criteria_organization_id'), 'policy_criteria', ['organization_id'], unique=False)
    op.create_table('readiness_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('overall_status', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highest_risk_items', sa.JSON(), nullable=False),
    sa.Column('recommended_next_steps', sa.JSON(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_reports_case_id'), 'readiness_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_readiness_reports_organization_id'), 'readiness_reports', ['organization_id'], unique=False)
    op.create_table('draft_letters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('letter_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('source_report_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['readiness_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_letters_case_id'), 'draft_letters', ['case_id'], unique=False)
    op.create_index(op.f('ix_draft_letters_organization_id'), 'draft_letters', ['organization_id'], unique=False)
    op.create_table('evidence_matches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('criterion_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_chunk_id', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_page', sa.String(length=64), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('missing_evidence', sa.JSON(), nullable=False),
    sa.Column('conflicting_evidence', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('reviewer_override_status', sa.String(length=64), nullable=True),
    sa.Column('reviewer_override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['policy_criteria.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_matches_case_id'), 'evidence_matches', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_matches_criterion_id'), 'evidence_matches', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_evidence_matches_organization_id'), 'evidence_matches', ['organization_id'], unique=False)
    op.create_table('citation_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('draft_letter_id', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=64), nullable=False),
    sa.Column('unsupported_claims', sa.JSON(), nullable=False),
    sa.Column('weakly_supported_claims', sa.JSON(), nullable=False),
    sa.Column('citation_errors', sa.JSON(), nullable=False),
    sa.Column('safe_to_show_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['prior_auth_cases.id'], ),
    sa.ForeignKeyConstraint(['draft_letter_id'], ['draft_letters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_checks_case_id'), 'citation_checks', ['case_id'], unique=False)
    op.create_index(op.f('ix_citation_checks_draft_letter_id'), 'citation_checks', ['draft_letter_id'], unique=False)
    op.create_index(op.f('ix_citation_checks_organization_id'), 'citation_checks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citation_checks_organization_id'), table_name='citation_checks')
    op.drop_index(op.f('ix_citation_checks_draft_letter_id'), table_name='citation_checks')
    op.drop_index(op.f('ix_citation_checks_case_id'), table_name='citation_checks')
    op.drop_table('citation_checks')
    op.drop_index(op.f('ix_evidence_matches_organization_id'), table_name='evidence_matches')
    op.drop_index(op.f('ix_evidence_matches_criterion_id'), table_name='evidence_matches')
    op.drop_index(op.f('ix_evidence_matches_case_id'), table_name='evidence_matches')
    op.drop_table('evidence_matches')
    op.drop_index(op.f('ix_draft_letters_organization_id'), table_name='draft_letters')
    op.drop_index(op.f('ix_draft_letters_case_id'), table_name='draft_letters')
    op.drop_table('draft_letters')
    op.drop_index(op.f('ix_readiness_reports_organization_id'), table_name='readiness_reports')
    op.drop_index(op.f('ix_readiness_reports_case_id'), table_name='readiness_reports')
    op.drop_table('readiness_reports')
    op.drop_index(op.f('ix_policy_criteria_organization_id'), table_name='policy_criteria')
    op.drop_index(op.f('ix_policy_criteria_case_id'), table_name='policy_criteria')
    op.drop_index('ix_criteria_case_code', table_name='policy_criteria')
    op.drop_table('policy_criteria')
    op.drop_index(op.f('ix_document_pages_organization_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_case_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_chunks_vector_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_case_id'), table_name='document_chunks')
    op.drop_index('ix_chunks_case_type', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index('ix_documents_case_type', table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_analysis_runs_run_type'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_organization_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_case_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_prior_auth_cases_status'), table_name='prior_auth_cases')
    op.drop_index(op.f('ix_prior_auth_cases_organization_id'), table_name='prior_auth_cases')
    op.drop_index('ix_cases_org_status', table_name='prior_auth_cases')
    op.drop_table('prior_auth_cases')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_index('ix_membership_user_org', table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
